### ISSUE TITLE
[Open] After updating the DDE-DOCK taskbar icons disappear

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/dde-dock#327]
Hello Team LinuxDeepin/DDE-DOCK

After updating the DDE-DOCK the taskbar icons disappear and on restart an error message appears with the following error message:

![Screen Capture_20201112175343](https://user-images.githubusercontent.com/32621790/99003232-81af6680-251c-11eb-80a1-676422ff8d65.png)

error message

![Screen Capture_20201112175157](https://user-images.githubusercontent.com/32621790/99003258-912eaf80-251c-11eb-8377-8341f16df7cc.png)

**Comment by mynameisjeffe** [comment]
I have the same error message! I'm using Deepin Manjaro.

**Comment by mynameisjeffe** [comment]
With the latest update, this is now fixed in my computer. 
I'm using deepin-dock 5.3.0.1701

**Comment by KimHono** [comment]
Yes, the 5.3.0.17-1 version was working well, BUT after updading to 5.3.0.19-2 the problem is back !
In my case:
- my docked applications icons disappeared, though without error message
- my taskbar thickness (width) preference was lost and is now minimalist with no choice to adjust

What about non-regression testing ?

**Comment by juteman** [comment]
https://github.com/linuxdeepin/package-tag/blob/master/packages-tag-version/packages-tag-1003-version.md

Hello, we fix dde-dock problem on 5.3.0.54, but the arch dde-dock tags is still 5.3.0.17 or 5.3.0.19.
U can wait for update.

**Comment by Cardellino** [comment]
Hello, dde-dock (taskbar) is displayed immediately after login. But with the double registration, the error is still there ....
-> Update Version deepin-dock 5.3.0.20-1 (5.3.0.19-2) <-
System Arch Linux

**Comment by KimHono** [comment]
> https://github.com/linuxdeepin/package-tag/blob/master/packages-tag-version/packages-tag-1003-version.md
> 
> Hello, we fix dde-dock problem on 5.3.0.54, but the arch dde-dock tags is still 5.3.0.17 or 5.3.0.19.
> U can wait for update.

I confirm : version 5.3.0.24-1 is working.
Thanks !

**Comment by serial02** [comment]
> I confirm : version 5.3.0.24-1 is working.
> Thanks !

Hello 

It seems that your statement is not true, as it remains the same situation as the previous version of dde-dock 5.3.023.1, as can be seen here: ( https://github.com/linuxdeepin/dde-dock/issues/325 )

Or in the following images:

![Screen Capture_select-area_20201129181930](https://user-images.githubusercontent.com/32621790/100554005-9146e300-3270-11eb-84c8-cc2be9fadbd0.png)

![Screen Capture_select-area_20201129182228](https://user-images.githubusercontent.com/32621790/100554010-9d32a500-3270-11eb-8b46-22575a2ece45.png)

Or maybe in this image Gif image:

![Screen Capture_select-area_20201129182248](https://user-images.githubusercontent.com/32621790/100554016-af144800-3270-11eb-9956-f3a48401dfd4.gif)

Still waiting for this important update:
Why not install the latest Deepin v20 1003 dde-dock ( dde-dock_5.3.0.54-1_amd64.deb ) on Archlinux Rolling? It only has a blurred bar at startup, but the other functions are better and more stable. Source: ( https://community-packages.deepin.com/deepin/pool/main/d/dde-dock/ )

**Comment by serial02** [comment]
Hello

New update of DDE-DOCK on this date being version 5.3.0.26.1 where inconsistencies and errors persist, as follows:

1º The restart and shutdown option no longer work.
2º The option to view the monitoring via the taskbar button no longer works.
3º The efficiency mode was corrected when selecting the other options, but when it is in efficiency mode and we click on the shutdown icon, the same situation of hiding the bar quickly remains.
4º The duplication of icons in the taskbar of the variety application remains.

![Screen Capture_dde-desktop_20201129190050](https://user-images.githubusercontent.com/32621790/100554857-81320200-3276-11eb-9325-7a52d4356596.png)

![Screen Capture_dde-desktop_20201129185719](https://user-images.githubusercontent.com/32621790/100554865-8c852d80-3276-11eb-93a1-a008bff61035.gif)

**Comment by Cardellino** [comment]
Hello,
The PC can only be rebooted or switched off via the console.
As serial02 has already written, icon no longer works ...
Can only confirm .....

**Comment by serial02** [comment]
Hello

After downgrading the startdde of the new version to be able to access the "system", the following error message appears again:

![Screen Capture_dde-desktop_20201130214401](https://user-images.githubusercontent.com/32621790/100682936-02ac9180-3356-11eb-88c6-d229509a8093.png)

**Comment by Cardellino** [comment]
I've been getting this error message since yesterday.
This morning I did a pacman -Syu update and now I can no longer log in. I keep getting the login mask ......
System Arch Linux

**Comment by serial02** [comment]
Hello

Dry logs to help them see if they can find a solution to this problem that has been going on for a long time.

[ArchLinux Rolling DDE-DOCK LOG.txt](https://github.com/linuxdeepin/dde-dock/files/5630510/ArchLinux.Rolling.DDE-DOCK.LOG.txt)

[ArchLinux Rolling LOG .txt](https://github.com/linuxdeepin/dde-dock/files/5630511/ArchLinux.Rolling.LOG.txt)

**Comment by KimHono** [comment]
> Hello,
> The PC can only be rebooted or switched off via the console.
> As serial02 has already written, icon no longer works ...
> Can only confirm .....
> System Arch Linux

That's true !
Version 5.3.0.24-1 was working, but the following are worse !
Now with 5.3.027-1 the shutdown button is non-reponsive, and there is this new one : "The plugin libdde-disk-mount-plugin.so is no compatible with the system".

System Arch 5.9.11-arch2-1

**Comment by Cardellino** [comment]
Problem still exists
the shutdown of the system is still not possible with a button.
I just hold out the system / restart only via console.
System Arch Linux
Kernel: 5.9.12-arch1-1

**Comment by smartsmallking** [comment]
I build dde-dock by tag 5.3.0.19 now. it works well on my machine
amd+deepin
sorry ,I do not have your programming environment

**Comment by KimHono** [comment]
Those icons problems are solved : https://github.com/linuxdeepin/dde-dock/issues/325#issuecomment-781140587
